export default {
  INIT_CHEST_MAPPING: 'INIT_CHEST_MAPPING',
  INIT_VOICE_MAPPING: 'INIT_VOICE_MAPPING',
  INIT_CHARACTER_MAPPING: 'INIT_CHARACTER_MAPPING',
  INIT_SKIN_MAPPING: 'INIT_SKIN_MAPPING',
  INIT_ITEM_MAPPING: 'INIT_ITEM_MAPPING',
  INIT_FAN_DESC_MAPPING: 'INIT_FAN_DESC_MAPPING',
  INIT_TITLE_MAPPING: 'INIT_TITLE_MAPPING',
}
